### ISSUE TITLE
[Feature Request] Remove alpha channel

### ISSUE THREAD

**Issue by Imerion** [lbalazscs/Pixelitor#145]
I often get pictures where I want to quickly remove the alpha channel and replace it with a single color. Some programs like GIMP have an option under the Image-section called "Remove Alpha Channel" that simply removes the alpha channel and replaces it with the chosen background color. If it's not too complicated I'd really like to see such a feature in Pixelitor.

**Comment by lbalazscs** [comment]
In an image the transparency information  is stored independently from the colors, in the "alpha channel".
In Pixelitor all image layers have an alpha channel - if they are not transparent, then the alpha channel is set to the maximum value of 255.
In Gimp it is possible to have images without an alpha channel. They can't have transparency, even the eraser tool erases them to the background color.
I don't plan to support this type of image in Pixelitor, because the user should not have to think about "alpha channels", it seems to me that it is more user-friendly if every image behaves consistently.

If I understand correctly, you don't really care about removing the alpha channel, you only want to replace the transparent parts with a given color. You can insert a new image layer bellow the layer with transparency (ctrl-clicking on the + button adds the new layer bellow the active) and after selecting it, you can fill it with the background color (ctrl-backspace). At the end merging down the original layer should result in a layer which looks like the Gimp layers without the alpha channel, even if it still has an alpha channel, and the erase tool can create transparency on them.

I intend to add a "Remove Transparency" filter that does these steps in one step. I think it is best if it is a filter without a dialog, because the replacement color would be the only option, and the background color can be used for that. Please confirm if this is what you need.

**Comment by Imerion** [comment]
Ah, I see, I didn't know Pixelitor worked that way. The reason I want to remove the alpha channel is to save space, for using these images on web pages. When using .png file size gets a tad smaller without the alpha channel. So I think the filter you describe won't work. But now that I understand the reason behind the way Pixelitor works, you don't have to change anything. I can solve this in another way the times I need it.

**Comment by lbalazscs** [comment]
If you care about the file size, then you would need something like "Export Optimized JPEG", but for PNG. The bad news is that this would be much more complicated than adding a filter. I did some experiments (without implementing it in the GUI), and I can save some space by not including the alpha channel, but not enough to be competitive with Gimp, making it useless. Gimp seems to use some advanced compression, and the Java libraries I found either use only basic compression or are buggy. 

BTW, if you don't have too many colors in your images, or if you don't care about exact colors, then using Indexed mode in Gimp (Image/Mode/Indexed) and then saving as PNG can result in much smaller images than removing the alpha channel. This is what sites like https://tinypng.com/ do.

**Comment by Imerion** [comment]
The Export Optimized JPEG function is great and I use it a lot too. I understand this is a lot of work, so don't worry about it. I have no problem opening another tool for these occasions. Saving in indexed mode is a great tip too - I often do that.

Thanks again for listening and testing this!

**Comment by lbalazscs** [comment]
I am thanking you for inspiring me to check out the newest java image file format libraries, because although I didn't find a very good compression, I found that I can add easily support for reading and writing TGA files - the last time I checked, this was not yet possible.
