### ISSUE TITLE
Does Pixelitor have something like Gimp's (Alpha to Select)?

### ISSUE THREAD

**Issue by Just-Another-Gnumer** [lbalazscs/Pixelitor#162]
The Gimp and Krita have the ability select around transparency using their wand and an "alpha to select" option.  Does Pixelitor 4.24 beta have something like this?

**Comment by lbalazscs** [comment]
No. The reason is that Pixelitor currently doesn't have the concept of partial, feathered selection. A point is either selected or not. When working with selections, there might be anti-aliasing at the edges, but that's all. A consequence is that only well-defined shapes (text, path) can be converted to a selection, but not fuzzy things like transparency.

On the other hand, layer masks can do everything selections can, and they can be fuzzy (they can contain shades of gray, and not only black and white). Layer masks also enable a much more flexible workflow (you can change them later), and for this reason I prefer using layer masks even in Gimp/Krita. If you describe what are you trying to achieve with the transparency-based selection, I can probably tell you how to achieve the same result with layer masks.

I wanted to finish by mentioning that you can convert transparency to a layer mask by using the menu "Layer/Layer Mask/Add from Transparency", but I see that this doesn't work as I expected (semi-transparent areas are not converted to gray)... This is a bug, and I hope that I will be able to fix it beta-2 (to be released in a few days).

**Comment by lbalazscs** [comment]
The bug mentioned above is fixed in beta-2, https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta2

**Comment by Just-Another-Gnumer** [comment]
Thank you for telling me about layer mask to mimic what I would have done with alpha to select.
