### ISSUE TITLE
I have an idea to promote drag and drop.

### ISSUE THREAD

**Issue by LinuxBeaver** [lbalazscs/Pixelitor#166]
I was thinking about a "drag and drop" watermark in the center of a non-canvas screen, but realized that would be kinda crude.

![image](https://user-images.githubusercontent.com/78667207/112365191-447b9200-8ccf-11eb-9fae-9ffeb3aaeb8c.png)

I made a mockup of the Java file select dialog telling the user they have the option of drag and drop. Could something like this be implemented?

**Comment by lbalazscs** [comment]
In general I think it's important to keep the user interface simple, because adding too much information can be scary for beginners or annoying for advanced users. That's why I removed some GUI shortcuts (like the "Original Image" background) when implementing #164, and this is also the reason I didn't add a discoverable Edit menu to the filter dialogs when implementing #165.

In this case I think we can assume that if a user is familiar with desktop apps in general, they will also try drag-and-dropping. I mean, all desktop apps that can open files also support drag-and-drop, don't they? 

There are some features that are hard to discover, for example if you drag-and-drop an image file into the layers panel at the right side, then it will be added as a new image layer, and not as a new image. This is documented only in the Help/Tip of the Day. 

If you want to contribute to the "Tips of the Day", you can do it by editing https://github.com/lbalazscs/Pixelitor/blob/master/src/main/resources/tips.properties

Or if you feel like creating any sort of tutorials or documentation, I'd be glad to help.

**Comment by Just-Another-Gnumer** [comment]
I knew about the layer drag and drop. I'll see what I can do regarding help tutorials. I was thinking about making Youtube Tutorials in the future, primarily focusing on Gimp.   However, Pixelitor and other tools (Inkscape, Gmic, Pytorch ML for image manipulation, were going to talked of as side tools used to assist Gimp in its weak areas. The whole idea is how to make basic design, youtube thumbnails and projects using open source software. 

![image](https://user-images.githubusercontent.com/78667207/112537936-2ed99b80-8da7-11eb-8d07-75355c15d58b.png)

**Comment by Just-Another-Gnumer** [comment]
For example, I made this spiral in Pixelitor and GMIC

![image](https://user-images.githubusercontent.com/78667207/112538659-043c1280-8da8-11eb-8864-aba714365ee1.png)

![image](https://user-images.githubusercontent.com/78667207/112538683-09995d00-8da8-11eb-8e93-e6adad8d3447.png)

![image](https://user-images.githubusercontent.com/78667207/112538702-0f8f3e00-8da8-11eb-9e5f-c1b70ffc2dc3.png)

![image](https://user-images.githubusercontent.com/78667207/112538734-16b64c00-8da8-11eb-9a44-a409ce55e5fe.png)

**Comment by lbalazscs** [comment]
I like your designs very much, and I would be interested in your youtube tutorials, even if they are not about Pixelitor :)
