### ISSUE TITLE
can undo one less action than specified in the setting when using the gradient tool

### ISSUE THREAD

**Issue by r3b3kka** [lbalazscs/Pixelitor#173]
Summary: can undo one less action than specified in the setting when using the gradient tool
	Severity: Major
	Priority: medium
	Environment: Windows 10, Java Environment 1.8.0, Pixelitor 4.2.3
	Steps for reproduced:
	1) open or create file
	2) use the gradient tool more than 4 times if the settings indicate 5(default)
	Result: only the last 4 actions will be canceled
	Expected result: can be canceled as many times as specified in the settings

**Comment by lbalazscs** [comment]
Un-hiding the handles also counts as an undo action. If you open View/Show History, you can see exactly is undone.

![history](https://user-images.githubusercontent.com/9939454/112400280-562d5b80-8d08-11eb-9c7b-e60e81afaf86.png)

In the future I might rewrite the undo system so that only image edits are counted when checking for the undo limit, but right now I don't see this as a bug.

**Comment by lbalazscs** [comment]
The undo system is improved in the final 4.3.0, which was just released.
