### ISSUE TITLE
[Feature request] Always display image size in status bar

### ISSUE THREAD

**Issue by Imerion** [lbalazscs/Pixelitor#188]
This is a minor feature request, but I sometimes find myself opening an image and immediately want to see its resolution. I usually just click Image -> Resize to see this, but it would be nice if image resolution would be displayed at all times in the status bar, perhaps to the left of the zoom controls.

Another option would be in the window title bar, after the image name, so it would read "Image.png (640 x 480) - Pixelitor 4.2.4".

**Comment by lbalazscs** [comment]
The status bar is not a good place in Pixelitor for information that is always present, because tool help messages are also displayed there, and on smaller screens the space is limited. However, after opening an image there is a "filename was opened" message, and if you want to see it only immediately after the opening, it could be displayed there.

I'm also thinking about displaying the size in the title bar or in the tab name/internal window title bar.

**Comment by Imerion** [comment]
I can agree the status bar is not optimal, but both title bar or tabs/internal window title bars are good ideas. In the "filename was opened" message would also work, since it's usually just after I've opened a new image I need that info. But having it available at all times in the window title bar / tab title bars would be even better.

**Comment by lbalazscs** [comment]
The size is now shown both in the window title and in the  "filename was opened" message.

**Comment by Imerion** [comment]
Excellent, thanks!
