### ISSUE TITLE
Smart Select/Select by Color (feature request)

### ISSUE THREAD

**Issue by r-mohammadi1** [lbalazscs/Pixelitor#213]
It should be fairly simple to implement given that the paint bucket tool already does 90% of what a smart select tool would need to. Would be a great QOL feature.

**Comment by lbalazscs** [comment]
Sadly, it's not simple to implement, but if you use layer masks instead of selections (they are more flexible anyway, because you can have any number of them on different layers), you can use Add/Replace from Color Range (under the Layer/Layer Mask menus), to achieve a similar effect. 

The problem with the implementation is that in Pixelitor (unlike in Photoshop or Gimp) selections are vector shapes, and not hidden raster masks. For a longer explanation see my comment at issue #162
