### ISSUE TITLE
"Ctrl-Z" does not work after using the "Crop tools" tool

### ISSUE THREAD

**Issue by Azirafel17** [lbalazscs/Pixelitor#25]
Reproducibility: Always
Severity: Minor
Priority: Medium
Software:
	Pixelitor 4.2.0
	Windows 10 64 Bit
	Java Version 1.8.0_221
Description:
after using the "Crop tools" tool you can not use the keyboard shortcut "Ctrl + Z" to cancel the action

Steps to reproduce:
1. Create a new picture with an arbitrary size and color background. For example: size-500px *500 px, background color-white
2. Select the "Crop tools"
3. Crop with image
4. Press "CTRL + Z"

**Comment by lbalazscs** [comment]
There is a missing feature that for multi-layer images some operations like crop, rotate, flip don't have undo. Do you mean this or you are also having problems with images that have only one layer? (undo after cropping in that case should work)

**Comment by Azirafel17** [comment]
1. there is one layer 
2.crop picture 
3.press CTRL-Z 
4. Nothing happens.

**Comment by lbalazscs** [comment]
Very strange... By "crop picture" you mean really cropping it (by pressing the "Crop" button, or double-click or pressing Enter), and not just drawing a crop rectangle, right? There is no undo for just drawing or adjusting the crop rectangle.

If you are really cropping it (the image becomes smaller), then please also check the following:

- The number of undo/redo levels in the "Edit/Preferences" menu is not set to zero
- Can you undo other things, like brush strokes?
- What happens if instead of pressing Ctrl-Z, you select manually the "Edit/Undo" menu? Is this menu perhaps grayed out?
- What do you see in the "View/Show History..." menu? (could you make a screenshot of it?)

**Comment by Azirafel17** [comment]
Я извиняюсь.

Проблема проявляется когда более одного слоя.

Когда используется 1 слой- то все ок.
Когда используется более, тогда баг.
![Screenshot_1](https://user-images.githubusercontent.com/54812116/65389109-ab3b8a80-dd7c-11e9-9a77-8c455978920b.jpg)

**Comment by lbalazscs** [comment]
I don't speak Russian, but based on google translate, I think I understood this. So you would like to have undo even with multi-layer images. I agree, this is how it should work.

**Comment by Azirafel17** [comment]
Right.
I believe that canceling an operation should always work.

**Comment by lbalazscs** [comment]
When I wrote the undo system for Pixelitor I decided not to add undo for operations that change multiple layers at the same time (including crop, rotate, flip) in order to save memory. I realized that this is not good, because it confuses users, but it is not easy to change, so the improvement won't come yet in 4.2.2

**Comment by lbalazscs** [comment]
Implemented in GitHub, there is now full undo for the actions that so far had undo only if there was only one image layer (Crop, Enlarge Canvas, Flip, Resize, Rotate). It will be in the next released version.

**Comment by lbalazscs** [comment]
Released in Pixelitor version 4.2.3.
