### ISSUE TITLE
There are no finite canvas size values when creating a new image

### ISSUE THREAD

**Issue by AlexHromi** [lbalazscs/Pixelitor#49]
Reproducibility: always
Severity: Minor
Priority: Medium
Software:
Pixelator 4.2.0
Windows 10 64 bit
Java Version 1.8.0_201
Description:

When creating a new image, the program did not set the final value of the canvas size. 

Playback Actions:

1.Create a new image
2. Enter value "99999" in the "Width" field
3. Enter value "99999" in the "Height" field
4. Press "OK" button

Expected Result:

Show error message with maximum field values

The result obtained:

Java error about lack of memory
Closing the application

**Comment by lbalazscs** [comment]
Well, it is impossible to set strict maximum values here, because the maximum size depends on the amount of RAM in your computer, the number of undo levels, the amount of layers you are going to use, etc. Theoretically even 99999*99999 should be possible with enough RAM. 

I will probably show some sort of warning here.

**Comment by lbalazscs** [comment]
Implemented in GitHub, it will be in the next version.
As it turns out, there is a limit independent of RAM:
![error1](https://user-images.githubusercontent.com/9939454/67974521-e26e4880-fc12-11e9-9553-7ba2c52dc9b0.png)
But the memory limit usually will come first:
![error2](https://user-images.githubusercontent.com/9939454/67974571-f87c0900-fc12-11e9-85c0-1760e507e925.png)

**Comment by lbalazscs** [comment]
Fixed in Pixelitor version 4.2.3, released today.
