### ISSUE TITLE
"Shapes Tool" and "Selection Tool"

### ISSUE THREAD

**Issue by OmarovAmir** [lbalazscs/Pixelitor#55]
Reproducibility: Always
Severity: Minor
Priority: Low
Software:
Pixelitor 4.2.0
Windows 7 Professional 64 Bit
Java Version 1.8.0_181

Description:
Selection action of Shapes Tool can't be canceled by click at some area like the same action of Selection Tool. In my opinion, would be better if this action can be canceled by click on "ESC" in both tools.

Steps to reproduce:
1. Create a new picture following example:
![Bug3_1](https://user-images.githubusercontent.com/55622089/65373547-17e55500-dca9-11e9-85aa-73a8bc437a17.jpg)
2. Select the "Selection Tool".
3. Click and drag to select the area.
![Bug3_2](https://user-images.githubusercontent.com/55622089/65373560-51b65b80-dca9-11e9-8764-3c32f1437165.jpg)
4. Click somewhere on area.
![Bug3_3](https://user-images.githubusercontent.com/55622089/65373585-cd180d00-dca9-11e9-9e56-7d5462ae2880.jpg)
5. Select the "Shapes Tool" and select Action "Selection" in the tools options.
6. Click and drag to select the area.
![Bug3_4](https://user-images.githubusercontent.com/55622089/65373635-4dd70900-dcaa-11e9-8cde-2083d0fc0b7b.jpg)
7. Click somewhere on area.
8. If you need to cancel selection action you must select the "Selection Tool" and click somewhere on area.
![Bug3_5](https://user-images.githubusercontent.com/55622089/65373688-c047e900-dcaa-11e9-9f86-f2252e50c727.jpg)

**Comment by lbalazscs** [comment]
Implemented in GitHub, it will be in the next released version. 

In version 4.2.1 the Shapes Tool will be pretty different from 4.2.1 (there are handles now, selections are converted) but I think the essence of this issue is implemented: the Shapes Tool works like the Gradient Tool, and Esc deselects in the Selection Tool.
Version 4.2.1 will be released soon, within a few days.

Selections can also always be removed by the Select/Deselect menu or by pressing Ctrl-D, but I agree that Esc must be more intuitive in some situations.

**Comment by lbalazscs** [comment]
This is implemented in Pixelitor version 4.2.1, released today.
