### ISSUE TITLE
Problem with holding "SPACE" down to move the entire selection

### ISSUE THREAD

**Issue by OmarovAmir** [lbalazscs/Pixelitor#56]
Reproducibility: Always
Severity: Major
Priority: High
Software:
Pixelitor 4.2.0
Windows 7 Professional 64 Bit
Java Version 1.8.0_181

Description:
Holding "SPACE" down to move the entire selection in Crop, Selection and Shapes Tools don't work on the laptops touchpad. I checked it on two laptops with high and low characteristics, but the same manufacturer Lenovo. May be it's hardware problem of laptops of this manufacturer.

Steps to reproduce:
1. By mouse.
[Mouse.zip](https://github.com/lbalazscs/Pixelitor/files/3638747/Mouse.zip)
2. By laptops touchpad.
[Touchpad.zip](https://github.com/lbalazscs/Pixelitor/files/3638749/Touchpad.zip)

**Comment by lbalazscs** [comment]
Haha, I saw the same issue with my (Samsung) laptop, but I also thought that this is so crazy that something must be wrong with my touchpad, and I didn't care because normally I use a real mouse anyway. I guess, I'll have to investigate this :)

**Comment by OmarovAmir** [comment]
Good luck! I hope you will fix it :)

**Comment by lbalazscs** [comment]
It turns out that this is a general _feature_ of touchpads, that they are disabled while typing in order to prevent accidental movement. It is discussed on many places on the internet, for example at https://superuser.com/questions/399341/touchpad-does-not-respond-when-i-am-holding-key-on-the-keyboard

In theory you should be able to switch off this feature, but this is driver-specific. Just search the web for "touchpad disabled while typing". 

Also note that in the Crop tool you can move the selection after the initial drag, and in version 4.2.1 (just a few days, and it will be released...) this will be also possible for the Shape tool. And in the selection tool, you can move the finished selection with the arrow keys and with shift-arrow for faster movement.
