### ISSUE TITLE
Move Tool: layer is duplicated after just right-click

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#83]
**Severity:** Minor
**Priority:** Low

**Description:** According to Move Tool hint in the status bar user should right-click+drag an image to duplicate a layer. However, right-clicking without dragging an image also duplicates a layer.

**Steps to reproduce:**

1. Open Pixelitor.
2. Create new image.
3. Press V.
4. Right-click the image.

**Expected result:** Nothing happens.
**Actual result:** Layer is duplicated. 

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
I understand that it seems useless to duplicate the layer if there is no dragging, but the problem is that a mouse click consists of a mouse press and a mouse release, and the layer should be duplicated already after a mouse press, but at this point it is not yet known whether the mouse will move before the mouse release. The only solution would be to remove the duplicated layer when the mouse is released if it turns out that there was no drag, but this behavior seems just as unintuitive as the original one, and there would be a surprising difference between  an unnoticed 1-pixel drag and no-drag, so I think the best is to do nothing about this.
