### ISSUE TITLE
Help to translate Pixelitor into Spanish

### ISSUE THREAD

**Issue by jEsuSdA** [lbalazscs/Pixelitor#97]
Hi again!
If you like, I can try to translate Pixelitor into Spanish.
Please send me the files and tell me how I can do that.
Thanks!

**Comment by jEsuSdA** [comment]
I see.
No problem. Take it as a no-hurry task. :D

Sending you a translation test:

[spanish.properties.zip](https://github.com/lbalazscs/Pixelitor/files/4429318/spanish.properties.zip)

Let me know if I have to made any correction. ;)

**Comment by lbalazscs** [comment]
OK, looks good. To be sure, I will change the code (tomorrow) so that these strings come from the file.

The left part doesn't have to be a full English user-readable string with escaped spaces, it is a programmer-friendly key, and the English GUI text will come from another file.
It's strange that you didn't include the ... sign in the Spanish text. Spanish GUIs don't use this convention? (It means that this menu will pop up a new window with settings and it's not just a command)

**Comment by jEsuSdA** [comment]
Nice. I forgot the ... In the translation. 😉

**Comment by jEsuSdA** [comment]
Updated:
[spanish.properties.txt](https://github.com/lbalazscs/Pixelitor/files/4430178/spanish.properties.txt)

**Comment by lbalazscs** [comment]
I checked in a version that can display the translated parts of the Edit menu in Spanish, see the screenshot bellow. It should detect the language settings of your operating system, but if it doesn't do it, you can also set the -Duser.language=es command-line flag, so that the complete command is:
`java -Duser.language=es -jar Pixelitor-4.2.3.jar `

![pix_spanish_edit_menu](https://user-images.githubusercontent.com/9939454/78437602-404a0500-7677-11ea-9f7e-4bd73bce6e02.png)

The translations are in the file https://github.com/lbalazscs/Pixelitor/blob/master/src/main/resources/texts_es.properties
The English-language file is https://github.com/lbalazscs/Pixelitor/blob/master/src/main/resources/texts.properties

Now comes the longer part... You should go though the entire GUI, and translate every text or message that you see and put it into the file texts_es.properties. As keys you can choose something relatively short but clear, with underscores (don't worry much about them, I will change the keys if I don't like them, the important part is the translation). It is not necessary to also update the English-language file texts.properties, I can do that part. It's not a problem if you forget or don't notice some text, I will let you know. But the goal must be to translate everything in the end, because otherwise the users are annoyed. If you don't understand some part of Pixelitor, just let me know. If you see something that you think that could be improved, just open an issue.

It would be nice if you also translated the "Tip of the Day" messages, although these are not so important as the rest of the GUI. If you translate them, please note that these are already in the .properties format in the https://github.com/lbalazscs/Pixelitor/blob/master/src/main/resources/tips.properties file, so the translation should be in a file called tips_es.properties, in the same directory and with the same keys.

If you need inspiration (or help with technical terms), the Gimp translations could help:
https://gitlab.gnome.org/GNOME/gimp/-/blob/master/po-libgimp/es.po

Or perhaps the Inkscape translations:
https://gitlab.com/inkscape/inkscape/-/blob/master/po/es.po?expanded=true&viewer=simple

I think the best would be if you forked the project, and then contributed your changes using the standard GitHub "pull requests". But it is also OK if you just attach the file here at this issue.

**Comment by lbalazscs** [comment]
The Gimp translations are in multiple files, the most useful is probably https://gitlab.gnome.org/GNOME/gimp/-/blob/master/po/es.po

**Comment by lbalazscs** [comment]
Closing this, as more up-to-date information is in the file https://github.com/lbalazscs/Pixelitor/blob/master/Translating.md
